<script type="text/javascript" src="js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="styles/bootstrap-4.1.2/popper.js"></script>
<script type="text/javascript" src="styles/bootstrap-4.1.2/bootstrap.min.js"></script>
<script type="text/javascript" src="plugins/greensock/TweenMax.min.js"></script>
<script type="text/javascript" src="plugins/greensock/TimelineMax.min.js"></script>
<script type="text/javascript" src="plugins/scrollmagic/ScrollMagic.min.js"></script>
<script type="text/javascript" src="plugins/greensock/animation.gsap.min.js"></script>
<script type="text/javascript" src="plugins/greensock/ScrollToPlugin.min.js"></script>
<script type="text/javascript" src="plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
<script type="text/javascript" src="plugins/easing/easing.js"></script>
<script type="text/javascript" src="plugins/progressbar/progressbar.min.js"></script>
<script type="text/javascript" src="plugins/parallax-js-master/parallax.min.js"></script>
<script type="text/javascript" src="js/custom.js"></script>
<script type="text/javascript" src="js/jquery.dataTables.js"></script>